version: "3.9"

services:
  working:
    build: ./working
    volumes:
      - ./storage:/storage
    command: ["tail", "-f", "/dev/null"]

  mysql:
    build: ./mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop_db

  php:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: always

volumes:
  db_data: {}
